#Add this code to $PROFILE if you don't want to use ISE theme.

$psISE.Options.ConsolePaneBackgroundColor = '#FF1E222F' 
$psISE.Options.ConsolePaneForegroundColor = '#FF9EE196' 
$psISE.Options.ConsolePaneTextBackgroundColor = '#FF272822'

$psISE.Options.ConsoleTokenColors['Attribute'] = '#FFFFFFFF'
$psISE.Options.ConsoleTokenColors['Command'] = '#FF66D9EF'
$psISE.Options.ConsoleTokenColors['CommandArgument'] = '#FFAE81FF'
$psISE.Options.ConsoleTokenColors['CommandParameter'] = '#FFA6E22E'
$psISE.Options.ConsoleTokenColors['Comment'] = '#FF6E715E'
$psISE.Options.ConsoleTokenColors['GroupEnd'] = '#FFFFFFFF'
$psISE.Options.ConsoleTokenColors['GroupStart'] = '#FFFFFFFF'
$psISE.Options.ConsoleTokenColors['Keyword'] = '#FFF92659'
$psISE.Options.ConsoleTokenColors['LineContinuation'] = '#FFFFFFFF'
$psISE.Options.ConsoleTokenColors['LoopLabel'] = '#FFAE81FF'
$psISE.Options.ConsoleTokenColors['Member'] = '#FFFD971F'
$psISE.Options.ConsoleTokenColors['NewLine'] = '#FF000000'
$psISE.Options.ConsoleTokenColors['Number'] = '#FFAE81FF'
$psISE.Options.ConsoleTokenColors['Operator'] = '#FFFFFFFF'
$psISE.Options.ConsoleTokenColors['Position'] = '#FF000000'
$psISE.Options.ConsoleTokenColors['StatementSeparator'] = '#FFFD971F'
$psISE.Options.ConsoleTokenColors['String'] = '#FFE6DB74'
$psISE.Options.ConsoleTokenColors['Type'] = '#FFFD971F'
$psISE.Options.ConsoleTokenColors['Unknown'] = '#FF000000'
$psISE.Options.ConsoleTokenColors['Variable'] = '#FFFFFFFF'

$psISE.Options.DebugBackgroundColor = '#00FFFFFF' 
$psISE.Options.DebugForegroundColor = '#FF00FFFF' 
$psISE.Options.ErrorBackgroundColor = '#00FFFFFF' 
$psISE.Options.ErrorForegroundColor = '#FFFF0000' 
$psISE.Options.VerboseBackgroundColor = '#00FFFFFF' 
$psISE.Options.VerboseForegroundColor = '#FF00FFFF' 
$psISE.Options.WarningBackgroundColor = '#00FFFFFF'
$psISE.Options.WarningForegroundColor = '#FFFF8C00' 


$psISE.Options.FontName = 'Consolas'
$psISE.Options.FontSize = 12

$psISE.Options.ScriptPaneBackgroundColor = '#FF272822' 
$psISE.Options.ScriptPaneForegroundColor = '#FFF8F8F2' 

$psISE.Options.TokenColors['Attribute'] = '#FFFFFFFF' 
$psISE.Options.TokenColors['Command'] = '#FF66D9EF' #
$psISE.Options.TokenColors['CommandArgument'] = '#FFAE81FF' 
$psISE.Options.TokenColors['CommandParameter'] = '#FFA6E22E' 
$psISE.Options.TokenColors['Comment'] = '#FF6E715E' 
$psISE.Options.TokenColors['GroupEnd'] = '#FFFFFFFF' 
$psISE.Options.TokenColors['GroupStart'] = '#FFFFFFFF' 
$psISE.Options.TokenColors['Keyword'] = '#FFF92659' 
$psISE.Options.TokenColors['LineContinuation '] = '#FFFFFFFF'
$psISE.Options.TokenColors['LoopLabel '] = '#FFAE81FF'
$psISE.Options.TokenColors['Member '] = '#FFFD971F'
$psISE.Options.TokenColors['NewLine '] = '#FF000000'
$psISE.Options.TokenColors['Number'] = '#FFAEC5FF' 
$psISE.Options.TokenColors['Operator '] = '#FFFFFFFF'
$psISE.Options.TokenColors['Position '] = '#FF000000'
$psISE.Options.TokenColors['StatementSeparator '] = '#FFFD971F'
$psISE.Options.TokenColors['String'] = '#FFE6DB74' 
$psISE.Options.TokenColors['Type '] = '#FFFD971F'
$psISE.Options.TokenColors['Unknown '] = '#FF000000'
$psISE.Options.TokenColors['Variable'] = '#FFFFFFFF' 


$psISE.Options.XmlTokenColors['Attribute'] = '#FFFF0000'
$psISE.Options.XmlTokenColors['CharacterData'] = '#FF808080'
$psISE.Options.XmlTokenColors['Comment'] = '#FF006400'
$psISE.Options.XmlTokenColors['CommentDelimiter'] = '#FF008000'
$psISE.Options.XmlTokenColors['ElementName'] = '#FF8B0000'
$psISE.Options.XmlTokenColors['MarkupExtension'] = '#FFFF8C00'
$psISE.Options.XmlTokenColors['Quote'] = '#FF0000FF'
$psISE.Options.XmlTokenColors['QuotedString'] = '#FF00008B'
$psISE.Options.XmlTokenColors['Tag'] = '#FF00008B'
$psISE.Options.XmlTokenColors['Text'] = '#FF000000'
